package ar.edu.unlam.pb1.interfaz.enums;

public enum MenuPrincipal {
	AGREGAR_PRODUCTO_A_LA_CARTA,
	MOSTRAR_CARTA_COMIDAS_ORDENADAS,
	MOSTRAR_CARTA_BEBIDAS_ORDENADAS,
	MODIFICAR_PRECIO_PRODUCTO,
	MODIFICAR_STOCK_PRODUCTO,
	ELIMINAR_PRODUCTO_DE_LA_CARTA,
	AGREGAR_RESERVA,
	VENDER_PRODUCTOS,
	VER_DISPONIBILIDAD_DE_MESAS,
	MOSTRAR_RESUMEN_RESERVAS_Y_SALIR
}
